version: "3.8"
services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.2-fpm-with-composer
    container_name: test-php
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    networks:
      - nginx
      - database

networks:
  nginx:
    external:
      name: nginx
  database:
    external :
      name: mysql-development
    