version: "3.8"
services:
  app:
    image: php-laravel:8.2
    container_name: kuitansi-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    networks:
      - database

networks:
  database:
    external :
      name: mysql-development
